class TaskNotFoundError(Exception):
    pass

class UserNotFoundError(Exception):
    pass